variables:
  solutionFolder: 'src/entityframeworkcore'

trigger:
  paths:
    include:
      - 'src/entityframeworkcore'
  branches:
   include:
      - "*"

pool:
  vmImage: 'windows-2022'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.1'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
- task: UseDotNet@2
  displayName: 'Install .NET 5'
  inputs:
    packageType: 'sdk'
    version: '5.x'
- task: UseDotNet@2
  displayName: 'Install .NET 6'
  inputs:
    packageType: 'sdk'
    version: '6.x'
- task: UseDotNet@2
  displayName: 'Install .NET 7'
  inputs:
    packageType: 'sdk'
    version: '7.x'
- task: UseDotNet@2
  displayName: 'Install .NET 8'
  inputs:
    packageType: 'sdk'
    version: '8.x'


- task: PowerShell@1
  displayName: 'Set Branch Quality'
  inputs:
    scriptType: inlineScript
    inlineScript: |
      if ($env:BUILD_SOURCEBRANCHNAME -eq "Develop"){
        Write-Output ("##vso[build.updatebuildnumber]" + $env:BUILD_BUILDNUMBER+"-beta")
      }
      else 
      {
        if ($env:BUILD_SOURCEBRANCHNAME -ne "master"){
          Write-Output ("##vso[build.updatebuildnumber]" + $env:BUILD_BUILDNUMBER+"-alpha")
        }
      }
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(solutionFolder)
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: $(solutionFolder)
    arguments: '--no-restore --configuration $(Build.Configuration) /p:ContinuousIntegrationBuild=true /p:BuildNumber=$(Build.BuildNumber)'
- task: PowerShell@2
  displayName: 'sqllocaldb start'
  inputs:
    targetType: 'inline'
    script: 'sqllocaldb start mssqllocaldb'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: $(solutionFolder)
    arguments: '--no-restore --no-build --configuration $(Build.Configuration) /p:ContinuousIntegrationBuild=true /p:BuildNumber=$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: $(solutionFolder)/**/*.csproj
    arguments: '--no-restore --no-build --configuration $(Build.Configuration) --output $(Build.ArtifactStagingDirectory) /p:ContinuousIntegrationBuild=true /p:BuildNumber=$(Build.BuildNumber)'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'publish packages'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'
