variables:
  solutionFolder: 'src/fluentmigrator'

trigger:
  paths:
    include:
      - 'src/fluentmigrator'
  branches:
   include:
      - "*"

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(solutionFolder)
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: $(solutionFolder)
    arguments: '--no-restore --configuration $(Build.Configuration) /p:ContinuousIntegrationBuild=true /p:BuildNumber=$(Build.BuildId)'
- task: DotNetCoreCLI@2
  enabled: false
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: $(solutionFolder)
    arguments: '--no-restore --no-build --configuration $(Build.Configuration) /p:ContinuousIntegrationBuild=true /p:BuildNumber=$(Build.BuildId)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: $(solutionFolder)/**/*.csproj
    arguments: '--no-restore --no-build --configuration $(Build.Configuration) --output $(Build.ArtifactStagingDirectory) /p:ContinuousIntegrationBuild=true /p:BuildNumber=$(Build.BuildId)'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'publish packages'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'
